name: Convert HTML Report to JUnit XML

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Convert HTML to JUnit XML
        run: |
          mkdir -p test-results
          python <<'EOF'
          from bs4 import BeautifulSoup

          with open("full_status.html") as f:
              soup = BeautifulSoup(f, "html.parser")

          with open("test-results/report.xml", "w") as f:
              f.write('<testsuites>\n')
              f.write('  <testsuite name="VectorCAST Results">\n')

              for row in soup.find_all("tr"):
                  cols = [td.get_text(strip=True) for td in row.find_all("td")]
                  if len(cols) >= 2:
                      test_name = cols[0]
                      status_text = cols[1].lower()

                      if status_text in ["pass", "passed", "success"]:
                          f.write(f'    <testcase name="{test_name}"/>\n')
                      elif status_text in ["fail", "failed", "error"]:
                          f.write(f'    <testcase name="{test_name}"><failure message="Failed"/></testcase>\n')
                      else:
                          f.write(f'    <testcase name="{test_name}"><skipped/></testcase>\n')

              f.write('  </testsuite>\n')
              f.write('</testsuites>\n')
          EOF

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ !cancelled() }}
        with:
          files: |
            test-results/**/*.xml
